apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion
spec:
  selector:
    matchLabels:
      app: currency-conversion
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - name: currency-conversion
        image: deeksha810/currency-conversion:1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8092
