spring:
 application:
  name: currency-conversion
  
server:
 port: 8092
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      refresh:
        enable: false

logging:
  level:
    org.springframework.web: DEBUG